name: Test

on:
  push:
    branches: [master]
    tags:
      - "**"
  pull_request:
    branches: [master]

    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: sleep 30
      - name: Test
        run: echo 'd'