name: Test

on:
  push:
    branches: [main]
    tags:
      - "**"
  pull_request:
    branches: [main]

    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "pending",
            "context": "${{ github.workflow }}",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail
      - name: Test
        run: sleep 30
      - name: Test
        run: echo 'd'
      - name: Create status
        if: always()
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "${{ github.workflow }}",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail
